# Generated by Django 6.0.6 on 2026-06-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=100)),
                ('mesaj', models.TextField()),
                ('dosya', models.ImageField(upload_to='anilar/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim_soyisim', models.CharField(max_length=100)),
                ('mesaj', models.TextField()),
                ('dosya', models.FileField(upload_to='anilar/')),
            ],
        ),
    ]
