# Generated by Django 6.0.6 on 2026-06-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dugun_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anilar',
        ),
    ]
