# Generated by Django 6.0.6 on 2026-07-07 10:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dugun_app', '0002_delete_anilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ani',
            name='dosya',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
